export { default as MailIcon } from "./MailIcon"
export { default as GithubIcon } from "./GithubIcon"
export { default as LinkedInIcon } from "./LinkedInIcon"
export { default as SwitchIcon } from "./SwitchIcon"
export { default as DownIcon } from "./DownIcon"
