import {
  jsPath,
  nodejsPath,
  phpPath,
  sassPath,
  bootstrapPath,
  materializePath,
  bulmaPath,
  reactPath,
  vuejsPath,
  angularPath,
  jqueryPath,
  apolloPath,
  expressPath,
  nextjsPath,
  laravelPath,
  graphqlPath,
  mongodbPath,
  mysqlPath,
  postgresqlPath,
  gitPath,
  githubPath,
  herokuPath,
  postmanPath,
  jsonPath
} from '../imagePaths';

const
  js = { title: "JavaScript", logo: jsPath, link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
  nodejs = { title: "Node.js", logo: nodejsPath, link: 'https://nodejs.org/en/' },
  php = { title: "PHP", logo: phpPath, link: 'https://www.php.net/' },
  sass = { title: "SASS", logo: sassPath, link: 'https://sass-lang.com/' },
  bootstrap = { title: "Bootstrap", logo: bootstrapPath, link: 'https://getbootstrap.com/' },
  materialize = { title: "Materialize", logo: materializePath, link: 'https://materializecss.com/' },
  bulma = { title: "Bulma", logo: bulmaPath, link: 'https://bulma.io/' },
  react = { title: "React", logo: reactPath, link: 'https://reactjs.org/' },
  vuejs = { title: "Vue.js", logo: vuejsPath, link: 'https://vuejs.org/' },
  angular = { title: "Angular", logo: angularPath, link: 'https://vuejs.org/' },
  jquery = { title: "jQuery", logo: jqueryPath, link: 'https://jquery.com/' },
  apollo = { title: "Apollo", logo: apolloPath, link: 'https://www.apollographql.com/' },
  express = { title: "Express", logo: expressPath, link: 'https://expressjs.com/' },
  nextjs = { title: "Next.js", logo: nextjsPath, link: 'https://nextjs.org/' },
  laravel = { title: "Laravel", logo: laravelPath, link: 'https://laravel.com/' },
  graphql = { title: "GraphQL", logo: graphqlPath, link: 'https://graphql.org/' },
  mongodb = { title: "MongoDB", logo: mongodbPath, link: 'https://www.mongodb.com/' },
  mysql = { title: "MySQL", logo: mysqlPath, link: 'https://www.mysql.com/' },
  postgresql = { title: "PostgreSQL", logo: postgresqlPath, link: 'https://www.postgresql.org/' },
  git = { title: "Git", logo: gitPath, link: 'https://git-scm.com/' },
  github = { title: "GitHub", logo: githubPath, link: 'https://github.com/' },
  heroku = { title: "Heroku", logo: herokuPath, link: 'https://www.heroku.com/' },
  postman = { title: "Postman", logo: postmanPath, link: 'https://www.getpostman.com/' },
  json = { title: "JSON", logo: jsonPath, link: 'https://www.json.org/' }

export {js, nodejs, php, sass, bootstrap, materialize, bulma, react, vuejs, angular, jquery, apollo, express, nextjs, laravel, graphql, mongodb, mysql, postgresql, git, github, heroku, postman, json};
